### ISSUE TITLE
Minor typo in readme

### ISSUE THREAD

**Issue by wrljet** [ibara/8088ify#2]
In this sentence: "It may be lesser-known that Intel had the porting of 8080 **assmebly** code to 8086/8088 in mind when designing the 8086/8088."

**Comment by ibara** [comment]
Fixed. Thanks.

**Comment by wrljet** [comment]
Cool project, BTW!

Microsoft supposedly/evidently used something similar back in their founding days.
They put a GW-BASIC on GitHub a while back, which I read had been largely mechanically translated from 8080.
